services:
  - type: web
    name: telegram-ocr-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: POPPLER_PATH
        value: /usr/bin
    autoDeploy: true
