services:
  - type: web
    name: telegram-ocr-bot
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: POPPLER_PATH
        value: /usr/bin
